use std::collections::HashSet;
use std::fs::File;
use std::io::{BufRead, BufReader, BufWriter, Write};
use std::path::Path;

/// Custom titlecase mappings for special attribute names
pub static CUSTOM_PASCAL_MAPPINGS: &[(&str, &str)] = &[
    ("role", "AccessibilityRole"),
    ("aria-label", "AccessibilityTitle"),
    ("aria-description", "AccessibilityDescription"),
    ("aria-details", "AccessibilityHelpText"),
    ("data-testid", "DataTestId"),
    ("uilayoutstype", "Uilayoutstype"),
    ("onupdate:modelvalue", "ModelValueUpdate"),
];

/// Convert a kebab-case or lowercase string to PascalCase for C++ enum variants
pub fn to_pascal_case(s: &str) -> String {
    for &(key, value) in CUSTOM_PASCAL_MAPPINGS {
        if s == key {
            return value.to_string();
        }
    }

    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '-' || c == ':' || c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    if result
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        result = format!("_{}", result);
    }

    result
}

/// Check if a string is a valid C++ identifier
pub fn is_valid_cpp_identifier(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    let first = s.chars().next().unwrap();
    if !first.is_ascii_alphabetic() && first != '_' {
        return false;
    }
    s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Process local names from a file and return deduplicated, sorted entries
/// Returns Vec of (lowercase_name, pascal_case_name)
pub fn process_local_names(local_names_path: &Path) -> Vec<(String, String)> {
    let file = File::open(local_names_path)
        .unwrap_or_else(|_| panic!("Failed to open {}", local_names_path.display()));
    let reader = BufReader::new(file);

    let mut seen = HashSet::new();
    let mut entries: Vec<(String, String)> = Vec::new();

    for line in reader.lines() {
        let name = line.unwrap();
        let lower = name.to_ascii_lowercase();
        if lower.is_empty() {
            continue;
        }
        if seen.insert(lower.clone()) {
            let pascal = to_pascal_case(&lower);
            if !is_valid_cpp_identifier(&pascal) {
                continue;
            }
            entries.push((lower, pascal));
        }
    }

    // Sort by PascalCase name for consistent C++ enum order
    entries.sort_by(|a, b| a.1.cmp(&b.1));
    entries
}

/// Generate the Rust attribute mappings file for blitz-bindings
pub fn generate_attribute_mappings(entries: &[(String, String)], out_dir: &Path) {
    let mapping_path = out_dir.join("attribute_mappings.rs");
    let mut file = BufWriter::new(File::create(mapping_path).unwrap());

    writeln!(
        file,
        r#"// Auto-generated attribute mappings - DO NOT EDIT
// This file is generated from web_atoms/local_names.txt

/// Ordered list of attribute strings matching the C++ Attribute enum order
pub static ATTRIBUTE_STRINGS: &[&str] = &["#
    )
    .unwrap();

    for (name, _pascal) in entries {
        writeln!(file, r#"    "{name}","#).unwrap();
    }

    writeln!(
        file,
        r#"];

/// Get attribute string by ID (returns None if ID is out of range)
pub fn get_string_by_id(id: u16) -> Option<&'static str> {{
    ATTRIBUTE_STRINGS.get(id as usize).copied()
}}

/// Get attribute ID by string (returns None if not found)
pub fn get_id_by_string(name: &str) -> Option<u16> {{
    // Linear search since the list is sorted by PascalCase name, not original string
    ATTRIBUTE_STRINGS
        .iter()
        .position(|&s| s == name)
        .map(|i| i as u16)
}}
"#
    )
    .unwrap();
}

/// Generate C++ header file for Attribute enum
pub fn generate_cpp_attributes(entries: &[(String, String)], output_dir: &Path) {
    let header_path = output_dir.join("ui_attributes.h");
    let mut header = BufWriter::new(File::create(header_path).unwrap());

    writeln!(
        header,
        r#"// Auto-generated by web_atoms build.rs - DO NOT EDIT
#pragma once

#include <cstdint>

namespace ui::dom {{

/// Enum representing HTML/SVG attribute and element names.
/// These values correspond to Blitz's internal LocalName atoms.
/// String conversions are done via Rust FFI (blitz::attribute_to_string, etc.)
enum class Attribute : uint16_t
{{"#
    )
    .unwrap();

    for (i, (_name, pascal)) in entries.iter().enumerate() {
        writeln!(header, "    {} = {},", pascal, i).unwrap();
    }

    writeln!(
        header,
        r#"}};

constexpr size_t attributeCount = {};

}} // namespace ui::dom"#,
        entries.len()
    )
    .unwrap();
}
